force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Object representing an Invoice under an Account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>cInvoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this Invoice is Active and is included in the Account summary</description>
    <inlineHelpText>If checked, this Invoice is Active and is included in the Account summary</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHandler.cls
public with sharing class InvoiceTriggerHandler {
    public InvoiceTriggerHandler() {

    }

    public static void beforeUpdateHandler(Map<Id, Invoice__c> oldMap, Map<Id, Invoice__c> newMap){
        //(Tony - 09/19/2022) prevent invoices from being updated if they were not set to active before the update
        preventUpdateInactiveInvoice(oldMap, newMap);
    }

    public static void preventUpdateInactiveInvoice(Map<Id, Invoice__c> oldMap, Map<Id, Invoice__c> newMap){
        for(Id key : oldMap.keySet()){
            if(oldMap.get(key).Active__c == false && newMap.get(key).Active__c == false){
                newMap.get(key).addError('Invoice cannot be updated while it is Inactive. Please mark the invoice "Active" and try again');
            }
        }
    }
}